#+STARTUP: indent
#+TITLE: Математика - 6й класс - задание 2
#+AUTHOR: %%AUTHOR%%
#+OPTIONS: toc:nil
#+DATE: 17 декабря 2017
#+LaTeX_CLASS_OPTIONS: [article,a4paper,times,11pt,margin=0.7in]
#+LATEX_HEADER: \usepackage[margin=0.3in]{geometry}
#+LaTeX_HEADER: \usepackage[utf8]{inputenc}
#+LaTeX_HEADER: \usepackage[main=russian]{babel}

* Задача 1
В сумме Геракл прошел 0,7 всего пути, поэтому 0,2 всего пути составляет 6км.
Получаем, что весь путь был $6\times10/2 = 30$ км.
* Задача 2
Первый станок проработал $\frac{135}{30}=4\frac{1}{2}$ часов,
а второй - $\frac{135}{45} = 3 часа$. Поэтому первый закончил работу в
$9 + 4\frac{1}{2} = 13\frac{1}{2}$ часов (1:30 дня),
так же как и второй: $9 + 1\frac{1}{2} + 3 = 13\frac{1}{2}$
* Задача 3
Медведь тяжелее тигра на два веса волка, так что вес волка $w = \frac{80}{2} = 40$ кг.
Получаем вес тигра $t = 8\times 40 = 400$ кг, вес медведя $m = 10\times 40 = 400$ кг.
* Задача 4
Составим систему уравнений: если Ниф-Ниф собрал $x$ яблок, Нуф-Нуф - $y$ яблок, Наф-Наф - $z$ яблок,
то $x+y+z=154$. Также $x-\frac{1}{3}x = \frac{2}{3}x = y-24 = z-18$.
Получаем $x = \frac{3}{2}z-27$ и $y = z+6$.
Подставим в первое уравнение: $\frac{3}{2}z-27 + z + 6 + z = 154$, $\frac{7}{2}z = 175$.
Ответ: $z = 50$, $y = 56$, $x = 48$.
* Задача 5
Составим систему уравнений: $138 = з + с$, $1080 = 10\cdot з + 6\cdot с$.
Подставим $з$ во второе уравнение: $1080 = 1380 - 10с + 6с = 1380 - 4c$.
Получаем, что Баба Яга купила $с = 75$ дм синего и 63 дм зелёного шелка.
* Задача 6
Вес бензина в $\frac{3}{4}$ цистерны составляет $87\frac{1}{2} - 33\frac{1}{2} = 54$ тонны,
поэтому масса пустой цистерны равна $33\frac{1}{2} - \frac{54}{3} = 15\frac{1}{2}$ тонн.
* Задача 7
Во второй месяц Ихтиандр собрал $\frac{4}{3}=1+\frac{1}{3}$ от того, что было
собрано в первый месяц, то есть на треть больше. Получается, что в
первый месяц он собрал $960\times3=2880$ жемчужин, а во второй - $960\times4=3840$.
* Задача 8
Масса всего шара = масса оболочки + масса гондолы + масса горелки =
$(240+320)+240+(240-150) = 240\times3+170 = 890$ кг.
* Задача 9
Среднее этих чисел равно
$\frac{84+\frac{4}{5}\times84+\frac{3}{5}\times\frac{4}{5}\times84}{3} =
\frac{84}{3}\times\left(\frac{25}{25}+\frac{20}{25}+\frac{12}{25}\right)
= 28\times\frac{57}{25} = \frac{1596}{25} = 63\frac{21}{25}$
* Задача 10
Какао было взято 7-3=4 части, итого какао и сахара вместе - 7+7-3=11
частей. Масса каждой части $\frac{8.8}{11}=0.8$ кг, то есть молока
надо взять $20\times0.8=16$ кг.
* Задача 11
После первого дня осталось $\frac{3}{8}\times240$ яблок, после
второго - $\frac{3}{8}\times\frac{3}{5}\times240 =
\frac{9}{40}\times240 = 54$ яблок. Они и были проданы за третий день.
* Задача 12
- Сила Кошки равна $6$ силам мышки,
- Сила Жучки  - $6\cdot5=30$,
- Сила Внучки - $6\cdot5\cdot4=120$,
- Сила Бабки  - $6\cdot5\cdot4\cdot3\cdot2=360$,
- Сила Деда   - $2\cdot3\cdot4\cdot5\cdot6 = 6! = 720$ сил Мышки,
- Все вместе (включая Мышку) они тянут с силой
  $720+360+120+30+6+1=1137$ мышек.
* Задача 13
Саша отдал
$\frac{5}{12}=\frac{19\times5}{12\times19}=\frac{95}{12\times19}$
часть денег, а Вася -
$\frac{7\times12}{12\times19}=\frac{84}{12\times19}<\frac{95}{12\times19}$. Поэтому
у Васи осталось больше денег.
* Задача 14
Последние $16$ страниц - это $\frac{2}{3}$ от того, что оставалось в
начале второго дня. Поэтому $\frac{1}{4}$ книги - это
$15+\frac{3}{2}\times16=15+24=39$ страниц. Получается, что в книге
$4\times39=156$ страниц.
* Задача 15
Каждый окунь, который Алиса отбирает у Базилио, уменьшает разницу на
2: у Базилио становится окунем меньше, а у Алисы - больше. После 5
окуней у них будет рыб поровну, а отобрав остальных 31 окуня, у Алисы
окажется на $31\times2=62$ больше.
